export const ADD_TO_CART = 'CART/ADD_TO_CART'
export const REMOVE_ITEM = 'CART/REMOVE_ITEM'
export const ADD_ONE = 'CART/ADD_ONE'
export const REMOVE_ONE = 'CART/REMOVE_ONE'
export const CLEAR_CART = 'CART/CLEAR_CART'

export const ADD_TO_FAVORITE = 'FAVORITE/ADD_TO_FAVORITE'
export const REMOVE_FROM_FAVORITE = 'FAVORITE/REMOVE_FROM_FAVORITE'

export const MAKE_ORDER = 'ORDER/MAKE_ORDER'
